In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
movies=pd.read_csv('indian movies.csv')
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50602 entries, 0 to 50601
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           50602 non-null  object
 1   Movie Name   50602 non-null  object
 2   Year         49041 non-null  object
 3   Timing(min)  50602 non-null  object
 4   Rating(10)   50602 non-null  object
 5   Votes        50602 non-null  object
 6   Genre        50602 non-null  object
 7   Language     50602 non-null  object
dtypes: object(8)
memory usage: 3.1+ MB

In [7]:
movies.shape

(50602, 8)

In [22]:
movies.replace('-', pd.NA, inplace=True)

In [23]:
movies.isnull().sum()

ID               958
Movie Name         0
Year               0
Timing(min)    24700
Rating(10)     25366
Votes          25365
Genre           8478
Language           0
dtype: int64

In [ ]:
movies.isnull().sum()

movies.dropna(inplace=True)

In [15]:
movies.isnull().sum()

ID             0
Movie Name     0
Year           0
Timing(min)    0
Rating(10)     0
Votes          0
Genre          0
Language       0
dtype: int64

In [ ]:
movies.head()

np.int64(0)

In [25]:
movies = movies[['Movie Name', 'Genre', 'Language', 'Year']]
movies.head()

               Movie Name                                 Genre Language  Year
0             Dr. Shaitan                                  <NA>    hindi  1960
1              Nadir Khan                                  <NA>     urdu  1968
2  Apna Sapna Money Money  Comedy, Musical, Romance                hindi  2006
3          Aag Aur Sholay                                  <NA>     urdu  1987
4                 Parivar     Comedy, Drama, Family                hindi  1956

In [26]:
movies.isnull().sum()

Movie Name       0
Genre         8478
Language         0
Year             0
dtype: int64

In [27]:
movies.dropna(inplace=True)

In [28]:
movies['tags'] = (
    movies['Genre'] + " " +
    movies['Language'] + " " +
    movies['Year'].astype(str)
)

In [30]:
movies['tags']=movies['tags'].str.lower()
movies.head()

,Movie Name,Genre,Language,Year,tags
2,Apna Sapna Money Money,"Comedy, Musical, Romance",hindi,2006,"comedy, musical, romance hindi 2006"
4,Parivar,"Comedy, Drama, Family",hindi,1956,"comedy, drama, family hindi 1956"
5,Humraah: The Traitor,Thriller,hindi,2008,thriller hindi 2008
6,Jacqueline I Am Coming,Drama,hindi,2019,drama hindi 2019
7,A Mighty Heart,"Biography, Drama, History",urdu,2007,"biography, drama, history urdu 2007"

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [35]:
vectors=cv.fit_transform(movies['tags']).toarray()

In [36]:
print(vectors.shape)

(40563, 166)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity=cosine_similarity(vectors)

In [39]:
print(similarity.shape)

(40563, 40563)

In [47]:
def recommend(movie):

    if movie not in movies['Movie Name'].values:
        print("Movie not found")
        return

    movie_index = movies[movies['Movie Name'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:

        print(
            movies.iloc[i[0]]['Movie Name'],
            "-> Similarity Score:",
            round(i[1], 2)
        )

In [49]:
recommend('3 Idiots')

Dimple -> Similarity Score: 1.0
Do Jhoot -> Similarity Score: 1.0
Ek Hans Ka Jora -> Similarity Score: 1.0
Romeo in Sikkim -> Similarity Score: 1.0
Khushboo -> Similarity Score: 0.87